export const GRID = { cols: 100, rows: 100 };

const now = Date.now();

export const appConfig = {
  version: "1.0.0",

  workspace: {
    id: "workspace_1",
    name: "My SDUI IDE",
    description: "Mini VSCode + LeetCode",
    rootNodeId: "root",
    createdAt: now,
    updatedAt: now,
    owner: "local-user",
    version: "1.0.0",
  },

  layout: {
    sections: [
      {
        id: "header",
        type: "Header",
        visible: true,
        title: "Header",
        position: { colStart: 1, colEnd: 101, rowStart: 1, rowEnd: 7 },
        props: {},
        events: {},
      },
      {
        id: "tree",
        type: "FileTree",
        visible: true,
        title: "Explorer",
        position: { colStart: 1, colEnd: 21, rowStart: 7, rowEnd: 101 },
        props: {
          allowRename: true,
          allowDelete: true,
          allowAddFolder: true,
          allowAddFile: true,
        },
        events: {},
      },
      {
        id: "editor",
        type: "Editor",
        visible: true,
        title: "Editor",
        position: { colStart: 21, colEnd: 76, rowStart: 7, rowEnd: 71 },
        props: { readonly: false },
        events: {},
      },
      {
        id: "testCases",
        type: "TestCasePanel",
        visible: true,
        title: "Test Cases",
        position: { colStart: 76, colEnd: 101, rowStart: 7, rowEnd: 71 },
        props: {},
        events: {},
      },
      {
        id: "console",
        type: "ConsolePanel",
        visible: true,
        title: "Output",
        position: { colStart: 21, colEnd: 101, rowStart: 71, rowEnd: 101 },
        props: {},
        events: {},
      },
    ],
  },

  fileTree: {
    root: {
      id: "root",
      name: "Workspace",
      type: "folder",
      path: "/",
      parentId: null,
      expanded: true,
      children: ["folder_frontend", "folder_backend", "file_readme", "file_package_json"],
      metadataId: "meta_root",
      permissionId: "perm_root",
    },

    folder_frontend: {
      id: "folder_frontend",
      name: "Frontend",
      type: "folder",
      path: "/Frontend",
      parentId: "root",
      expanded: true,
      children: ["folder_src", "folder_public"],
      metadataId: "meta_frontend",
      permissionId: "perm_frontend",
    },

    folder_src: {
      id: "folder_src",
      name: "src",
      type: "folder",
      path: "/Frontend/src",
      parentId: "folder_frontend",
      expanded: true,
      children: ["file_app", "file_main", "file_tree_component"],
      metadataId: "meta_src",
      permissionId: "perm_src",
    },

    file_app: {
      id: "file_app",
      name: "App.jsx",
      type: "file",
      extension: "jsx",
      path: "/Frontend/src/App.jsx",
      parentId: "folder_src",
      contentId: "content_app",
      metadataId: "meta_app",
      permissionId: "perm_app",
    },

    file_main: {
      id: "file_main",
      name: "main.jsx",
      type: "file",
      extension: "jsx",
      path: "/Frontend/src/main.jsx",
      parentId: "folder_src",
      contentId: "content_main",
      metadataId: "meta_main",
      permissionId: "perm_main",
    },

    file_tree_component: {
      id: "file_tree_component",
      name: "FileTree.jsx",
      type: "file",
      extension: "jsx",
      path: "/Frontend/src/FileTree.jsx",
      parentId: "folder_src",
      contentId: "content_tree_component",
      metadataId: "meta_tree_component",
      permissionId: "perm_tree_component",
    },

    folder_public: {
      id: "folder_public",
      name: "public",
      type: "folder",
      path: "/Frontend/public",
      parentId: "folder_frontend",
      expanded: false,
      children: ["file_logo"],
      metadataId: "meta_public",
      permissionId: "perm_public",
    },

    file_logo: {
      id: "file_logo",
      name: "logo.png",
      type: "file",
      extension: "png",
      path: "/Frontend/public/logo.png",
      parentId: "folder_public",
      contentId: "content_logo",
      metadataId: "meta_logo",
      permissionId: "perm_logo",
    },

    folder_backend: {
      id: "folder_backend",
      name: "Backend",
      type: "folder",
      path: "/Backend",
      parentId: "root",
      expanded: false,
      children: ["file_server", "file_routes"],
      metadataId: "meta_backend",
      permissionId: "perm_backend",
    },

    file_server: {
      id: "file_server",
      name: "server.js",
      type: "file",
      extension: "js",
      path: "/Backend/server.js",
      parentId: "folder_backend",
      contentId: "content_server",
      metadataId: "meta_server",
      permissionId: "perm_server",
    },

    file_routes: {
      id: "file_routes",
      name: "routes.js",
      type: "file",
      extension: "js",
      path: "/Backend/routes.js",
      parentId: "folder_backend",
      contentId: "content_routes",
      metadataId: "meta_routes",
      permissionId: "perm_routes",
    },

    file_readme: {
      id: "file_readme",
      name: "README.md",
      type: "file",
      extension: "md",
      path: "/README.md",
      parentId: "root",
      contentId: "content_readme",
      metadataId: "meta_readme",
      permissionId: "perm_readme",
    },

    file_package_json: {
      id: "file_package_json",
      name: "package.json",
      type: "file",
      extension: "json",
      path: "/package.json",
      parentId: "root",
      contentId: "content_package_json",
      metadataId: "meta_package_json",
      permissionId: "perm_package_json",
    },
  },

  tabs: {
    activeTabId: "file_app",
    openTabs: [
      { fileId: "file_app", pinned: false, dirty: false }
    ],
  },

  search: {
    recentFiles: [],
    searchIndex: [],
  },

  settings: {
    theme: "dark",
    fontSize: 14,
    tabSize: 2,
    autoSave: true,
    wordWrap: true,
  },

  componentRegistry: {
    Header: { type: "Header", version: "1.0.0", props: {}, events: {} },
    FileTree: { type: "FileTree", version: "1.0.0", props: {}, events: {} },
    Editor: { type: "Editor", version: "1.0.0", props: {}, events: {} },
    TestCasePanel: { type: "TestCasePanel", version: "1.0.0", props: {}, events: {} },
    ConsolePanel: { type: "ConsolePanel", version: "1.0.0", props: {}, events: {} },
  },

  actionRegistry: {
    SAVE_FILE: { type: "SAVE_FILE" },
    RUN_TESTS: { type: "RUN_TESTS" },
    RUN_ACTIVE_FILE: { type: "RUN_ACTIVE_FILE" },
    OPEN_FILE: { type: "OPEN_FILE" },
    RENAME_NODE: { type: "RENAME_NODE" },
    DELETE_NODE: { type: "DELETE_NODE" },
    ADD_FILE: { type: "ADD_FILE" },
    ADD_FOLDER: { type: "ADD_FOLDER" },
    MOVE_NODE: { type: "MOVE_NODE" },
    DUPLICATE_NODE: { type: "DUPLICATE_NODE" },
    UNDO: { type: "UNDO" },
    REDO: { type: "REDO" },
  },

  fileContents: {
    content_app: {
      id: "content_app",
      fileId: "file_app",
      language: "javascript",
      size: 1024,
      content:
        "function solve(a, b) {\n  return a + b;\n}\n\nconsole.log(\"Hello from App.jsx\");\nconsole.log(solve(2, 3));\n",
      createdAt: now,
      updatedAt: now,
    },
    content_main: {
      id: "content_main",
      fileId: "file_main",
      language: "javascript",
      size: 256,
      content: "import React from 'react';\n",
      createdAt: now,
      updatedAt: now,
    },
    content_tree_component: {
      id: "content_tree_component",
      fileId: "file_tree_component",
      language: "javascript",
      size: 128,
      content: "function FileTree() {}\n",
      createdAt: now,
      updatedAt: now,
    },
    content_logo: {
      id: "content_logo",
      fileId: "file_logo",
      language: "binary",
      size: 64,
      content: "Image Placeholder",
      createdAt: now,
      updatedAt: now,
    },
    content_server: {
      id: "content_server",
      fileId: "file_server",
      language: "javascript",
      size: 256,
      content: "const express = require('express');\n",
      createdAt: now,
      updatedAt: now,
    },
    content_routes: {
      id: "content_routes",
      fileId: "file_routes",
      language: "javascript",
      size: 128,
      content: "export default [];\n",
      createdAt: now,
      updatedAt: now,
    },
    content_readme: {
      id: "content_readme",
      fileId: "file_readme",
      language: "markdown",
      size: 64,
      content: "Project Documentation\n",
      createdAt: now,
      updatedAt: now,
    },
    content_package_json: {
      id: "content_package_json",
      fileId: "file_package_json",
      language: "json",
      size: 64,
      content: '{"name":"sdui-project"}\n',
      createdAt: now,
      updatedAt: now,
    },
  },

  metadata: {
    meta_root: {
      id: "meta_root",
      createdAt: now,
      updatedAt: now,
      createdBy: "user",
      extension: "",
      encoding: "utf-8",
      size: 0,
      isHidden: false,
      isReadonly: false,
    },
    meta_frontend: {
      id: "meta_frontend",
      createdAt: now,
      updatedAt: now,
      createdBy: "user",
      extension: "",
      encoding: "utf-8",
      size: 0,
      isHidden: false,
      isReadonly: false,
    },
    meta_src: {
      id: "meta_src",
      createdAt: now,
      updatedAt: now,
      createdBy: "user",
      extension: "",
      encoding: "utf-8",
      size: 0,
      isHidden: false,
      isReadonly: false,
    },
    meta_public: {
      id: "meta_public",
      createdAt: now,
      updatedAt: now,
      createdBy: "user",
      extension: "",
      encoding: "utf-8",
      size: 0,
      isHidden: false,
      isReadonly: false,
    },
    meta_backend: {
      id: "meta_backend",
      createdAt: now,
      updatedAt: now,
      createdBy: "user",
      extension: "",
      encoding: "utf-8",
      size: 0,
      isHidden: false,
      isReadonly: false,
    },
    meta_app: {
      id: "meta_app",
      createdAt: now,
      updatedAt: now,
      createdBy: "user",
      extension: "jsx",
      encoding: "utf-8",
      size: 1024,
      isHidden: false,
      isReadonly: false,
    },
    meta_main: {
      id: "meta_main",
      createdAt: now,
      updatedAt: now,
      createdBy: "user",
      extension: "jsx",
      encoding: "utf-8",
      size: 256,
      isHidden: false,
      isReadonly: false,
    },
    meta_tree_component: {
      id: "meta_tree_component",
      createdAt: now,
      updatedAt: now,
      createdBy: "user",
      extension: "jsx",
      encoding: "utf-8",
      size: 128,
      isHidden: false,
      isReadonly: false,
    },
    meta_logo: {
      id: "meta_logo",
      createdAt: now,
      updatedAt: now,
      createdBy: "user",
      extension: "png",
      encoding: "binary",
      size: 64,
      isHidden: false,
      isReadonly: false,
    },
    meta_server: {
      id: "meta_server",
      createdAt: now,
      updatedAt: now,
      createdBy: "user",
      extension: "js",
      encoding: "utf-8",
      size: 256,
      isHidden: false,
      isReadonly: false,
    },
    meta_routes: {
      id: "meta_routes",
      createdAt: now,
      updatedAt: now,
      createdBy: "user",
      extension: "js",
      encoding: "utf-8",
      size: 128,
      isHidden: false,
      isReadonly: false,
    },
    meta_readme: {
      id: "meta_readme",
      createdAt: now,
      updatedAt: now,
      createdBy: "user",
      extension: "md",
      encoding: "utf-8",
      size: 64,
      isHidden: false,
      isReadonly: false,
    },
    meta_package_json: {
      id: "meta_package_json",
      createdAt: now,
      updatedAt: now,
      createdBy: "user",
      extension: "json",
      encoding: "utf-8",
      size: 64,
      isHidden: false,
      isReadonly: false,
    },
  },

  permissions: {
    perm_root: { id: "perm_root", read: true, write: true, rename: false, delete: false, move: false, execute: false },
    perm_frontend: { id: "perm_frontend", read: true, write: true, rename: true, delete: true, move: true, execute: false },
    perm_src: { id: "perm_src", read: true, write: true, rename: true, delete: true, move: true, execute: false },
    perm_public: { id: "perm_public", read: true, write: true, rename: true, delete: true, move: true, execute: false },
    perm_backend: { id: "perm_backend", read: true, write: true, rename: true, delete: true, move: true, execute: false },
    perm_app: { id: "perm_app", read: true, write: true, rename: true, delete: true, move: true, execute: true },
    perm_main: { id: "perm_main", read: true, write: true, rename: true, delete: true, move: true, execute: true },
    perm_tree_component: { id: "perm_tree_component", read: true, write: true, rename: true, delete: true, move: true, execute: true },
    perm_logo: { id: "perm_logo", read: true, write: false, rename: true, delete: true, move: true, execute: false },
    perm_server: { id: "perm_server", read: true, write: true, rename: true, delete: true, move: true, execute: true },
    perm_routes: { id: "perm_routes", read: true, write: true, rename: true, delete: true, move: true, execute: true },
    perm_readme: { id: "perm_readme", read: true, write: true, rename: true, delete: true, move: true, execute: false },
    perm_package_json: { id: "perm_package_json", read: true, write: true, rename: true, delete: true, move: true, execute: false },
  },

  history: {
    undoStack: [],
    redoStack: [],
  },

  problems: {
    currentProblem: "problem_1",
    entities: {
      problem_1: {
        id: "problem_1",
        title: "Two Sum",
        difficulty: "Easy",
        language: "javascript",
        starterFileId: "file_app",
      },
    },
  },

  runtime: {
    testCasesByFile: {
      file_app: [
        {
          id: "tc_1",
          input: "[2,3]",
          expected: "5",
          hidden: false
        }
      ]
    },

    executions: [],

    console: {
      logs: []
    },

    lastTestRun: null,
    activeExecutionId: null,
    running: false
  },
};
